### ISSUE TITLE
Name does not resolve (eztv1.xyz:443)

### ISSUE THREAD

**Issue by d3mystified** [knightcrawler-stremio/knightcrawler#216]
**Describe the bug**
Eztv crawler is failing.

**To Reproduce**
Running the latest container.

**Expected behavior**
It should work.

**Logs**
```
20:44:24 [Information] [Producer.Features.Crawlers.EzTv.EzTvCrawler] Starting "EZTV" crawl
20:44:24 [Error] [Quartz.Core.JobRunShell] Job CrawlersJobs.EzTvCrawler threw a JobExecutionException:
Parameters: refire = True, unscheduleFiringTrigger = False, unscheduleAllTriggers = False
 Quartz.JobExecutionException
 ---> System.Net.Http.HttpRequestException: Name does not resolve (eztv1.xyz:443)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Producer.Features.CrawlerSupport.BaseXmlCrawler.Execute() in /src/producer/src/Features/CrawlerSupport/BaseXmlCrawler.cs:line 16
   at Producer.Features.JobSupport.BaseJob.Execute(IJobExecutionContext context) in /src/producer/src/Features/JobSupport/BaseJob.cs:line 14
   --- End of inner exception stack trace ---
   at Producer.Features.JobSupport.BaseJob.Execute(IJobExecutionContext context) in /src/producer/src/Features/JobSupport/BaseJob.cs:line 18
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken) [See nested exception: System.Net.Http.HttpRequestException: Name does not resolve (eztv1.xyz:443)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Producer.Features.CrawlerSupport.BaseXmlCrawler.Execute() in /src/producer/src/Features/CrawlerSupport/BaseXmlCrawler.cs:line 16
   at Producer.Features.JobSupport.BaseJob.Execute(IJobExecutionContext context) in /src/producer/src/Features/JobSupport/BaseJob.cs:line 14]
20:44:24 [Error] [Quartz.Core.JobRunShell] Job CrawlersJobs.EzTvCrawler threw an unhandled Exception:
System.InvalidOperationException: Job failed too many times
   at Producer.Features.JobSupport.BaseJob.Execute(IJobExecutionContext context) in /src/producer/src/Features/JobSupport/BaseJob.cs:line 9
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
20:44:24 [Error] [Quartz.Core.ErrorLogger] Job CrawlersJobs.EzTvCrawler threw an exception.
```

**Hardware:**
 - OS and distro: Ubuntu
 - Server: Docker (bare metal)

**Additional context**
N/A

**Comment by FunkeCoder23** [comment]
not exactly a KC issue: https://downforeveryoneorjustme.com/eztv1.xyz

Do you know the new eztv hostname?
