### ISSUE TITLE
Can't get tv shows

### ISSUE THREAD

**Issue by lucawen** [knightcrawler-stremio/knightcrawler#224]
**Describe the bug**
Trying to search for some TV shows, I'm not finding any episodes of anything I was searching for, just movies.

**To Reproduce**
I'm currently running a private instance on elfhosting. To test, just search for any TV show

**Expected behavior**
It should return information about the content of the TV show

**Logs**
Addon:
```
app.kubernetes.io/name=knightcrawler-addon -f
Defaulted container "knightcrawler-addon" out of: knightcrawler-addon, gluetun
Defaulted container "knightcrawler-addon" out of: knightcrawler-addon, gluetun
imdbId tt0179225
imdbId tt29141112
imdbId tt4919268
imdbId tt0167261
imdbId tt21383812
imdbId tt15782954
imdbId tt19755790
imdbId tt30743549
```

Debrid Collector:
```
Defaulted container "knightcrawler-debridcollector" out of: knightcrawler-debridcollector, gluetun
04:54:37 [Information] [SharedContracts.Python.PythonEngineService] Python engine initialized
04:54:37 [Warning] [Microsoft.AspNetCore.Server.Kestrel] Overriding address(es) '"http://*:8080"'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
04:54:42 [Information] [MassTransit] Bus started: rabbitmq://rabbitmq/
04:54:57 [Information] [DebridCollector.Features.Worker.InfohashMetadataSagaStateMachine] Collecting Metadata for torrent "e2ddd9e6ebe17bbeeaf6fbcdab3a6ad63e8df41a" in Saga fff93657-14bf-4b08-afdc-c206db9a14a4
04:54:59 [Error] [DebridCollector.Features.Debrid.DebridRequestProcessor] Failed to process infoHashes
System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'Array'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonDocument.TryGetNamedPropertyValue(Int32 index, ReadOnlySpan`1 propertyName, JsonElement& value)
   at DebridCollector.Features.Debrid.RealDebridClient.GetMetadataAsync(IReadOnlyCollection`1 requests, CancellationToken cancellationToken) in /src/debrid-collector/Features/Debrid/RealDebridClient.cs:line 17
   at DebridCollector.Features.Debrid.DebridRequestProcessor.ProcessRequests(IReadOnlyCollection`1 requests, CancellationToken stoppingToken) in /src/debrid-collector/Features/Debrid/DebridRequestProcessor.cs:line 48
```

Producer:
 ```
 Defaulted container "knightcrawler-producer" out of: knightcrawler-producer, gluetun
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.InvalidOperationException: Job failed too many times
   at Producer.Features.JobSupport.BaseJob.Execute(IJobExecutionContext context) in /src/producer/src/Features/JobSupport/BaseJob.cs:line 9
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.InvalidOperationException: Job failed too many times
   at Producer.Features.JobSupport.BaseJob.Execute(IJobExecutionContext context) in /src/producer/src/Features/JobSupport/BaseJob.cs:line 9
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
04:57:47 [Information] [Producer.Features.Crawlers.Yts.YtsCrawler] Ingestion Successful - Wrote 0 new torrents
04:57:47 [Information] [Producer.Features.Crawlers.Tgx.TgxCrawler] Ingestion Successful - Wrote 0 new torrents
04:58:01 [Information] [Producer.Features.Amqp.PublisherJob] Successfully set 34 torrents as processed
```

**Hardware:**
 - OS and distro: Kubernetes on Linux
 - Server: Kubernetes

**Additional context**

**Comment by TheKing349** [comment]
I just set up knightcrawler and I have the same issue as well

**Comment by asynchronous98** [comment]
I have the same issue as well
